function s_wmcoverage_10hemisphere
% Compare white matter coverage of each optimized connectomes in grpup level.
% Script used for the visualization in Figure 3b in
% Takemura, H., Wandell, B. A & Pestilli, F. Ensemble Tractography.
%
% This example script simply load .mat files generated by s_comparewmcoverage.m in each subject,
% average those statistics to generate bar graph used in Figure 3b.
%
% Hiromasa Takemura (c) Stanford VISTA team, 2014

% Path to .mat file in individual subjects generated by s_comparewmcoverage.m
FascicledensityLoad{1} = 'S1_LH_Occipital_wmcoverage_5models.mat';
FascicledensityLoad{2} = 'S1_RH_Occipital_wmcoverage_5models.mat';
FascicledensityLoad{3} = 'S2_LH_Occipital_wmcoverage_5models.mat';
FascicledensityLoad{4} = 'S2_RH_Occipital_wmcoverage_5models.mat';
FascicledensityLoad{5} = 'S3_LH_Occipital_wmcoverage_5models.mat';
FascicledensityLoad{6} = 'S3_RH_Occipital_wmcoverage_5models.mat';
FascicledensityLoad{7} = 'S4_LH_Occipital_wmcoverage_5models.mat';
FascicledensityLoad{8} = 'S4_RH_Occipital_wmcoverage_5models.mat';
FascicledensityLoad{9} = 'S5_LH_Occipital_wmcoverage_5models.mat';
FascicledensityLoad{10} = 'S5_RH_Occipital_wmcoverage_5models.mat';

% Load data from individual subject, and make matrix restoring group data
for i = 1:10
    load(FascicledensityLoad{i});
    % Load proportion of white matter coverage
    propvoxelcovered_mean(:,i) = propvoxelcovered;
end

% Compute mean, sd and sem.
fdensity_mean_sum = mean(propvoxelcovered_mean,2);
fdensity_std_sum = std(propvoxelcovered_mean,0, 2);
fdensity_ser_sum = propvoxelcovered_mean/sqrt(10);

% Set font size
fontSiz = 16;

% Set verical axis
h1.ylim(1) = 0;
h1.ylim(2) = 3;

% Plot is
bar(fdensity_mean_sum);

hold on
% Overlay error bar (in this case, sem across 10 hemispheres)
errorbar(fdensity_mean_sum,fdensity_ser_sum,'r','linestyle','none','LineWidth',2);

% Set X axis label
set(gca,'XTickLabel',{'0.25','0.5','1','2','ETC'},'fontsize',fontSiz');

% Visualization settings
set(gca,'tickdir','out', ...
    'box','off', ...
    'ylim',h1.ylim);

% Set Y axis label
ylabel('Fascicles per voxel','fontsize',16);